# Pandas

Pandas is a Python library used for data manipulation and analysis. It provides data structures like DataFrames and Series, which are designed to make working with structured data easy and intuitive. It is built on top of NumPy and is well-suited for handling tabular data, time series data, and other forms of structured data. It allows for efficient data cleaning, transformation, merging, and analysis. It is widely used in various fields, including data science, finance, and engineering

Features of Pandas

1.Easy handling of missing data (represented as NaN, NA, or NaT) in floating point as well as non-floating point data

2.Size mutability: columns can be inserted and deleted from DataFrame and higher dimensional objects

3.Automatic and explicit data alignment: objects can be explicitly aligned to a set of labels, or the user can simply ignore the labels and let Series, DataFrame, etc. automatically align the data for you in computations

4.Powerful, flexible group by functionality to perform split-apply-combine operations on data sets, for both aggregating and transforming data

5.Make it easy to convert ragged, differently-indexed data in other Python and NumPy data structures into DataFrame objects

6.Intelligent label-based slicing, fancy indexing, and subsetting of large data sets

7.Time series-specific functionality: date range generation and frequency conversion, moving window statistics, date shifting and lagging

In [1488]:
import pandas as pd

A Pandas Series is like a column in a table.
It is a one-dimensional array holding data of any type

In [1489]:
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

In [1490]:
pd.Series([1,2,3],index=["one","two","three"])

one      1
two      2
three    3
dtype: int64

In [1491]:
a=pd.Series([1,2,3],index=["one","two","three"])#Row and series
b=pd.Series([3,4,5],index=["three","four","five"])
c=pd.concat((a,b))#concatination of two serirs
c

one      1
two      2
three    3
three    3
four     4
five     5
dtype: int64

DataFrame:-it exist in a tablular formate .It consist of rows and series


A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

In [1492]:
#keys can be anything, values should be in the form of list
students={"student Name":["sakshi","Rashi","diksha"],
          "class":[12,11,6],
          "subject":["Java","python","C+"]}
pd.DataFrame(students)

  student Name  class subject
0       sakshi     12    Java
1        Rashi     11  python
2       diksha      6      C+

In [1493]:
s={"Math":[34,67,97,34],
   "Science":[94,87,67,36],
   "English":[34,67,97,34]}

df=pd.DataFrame(s,index=["A","B","C","D"])
df

   Math  Science  English
A    34       94       34
B    67       87       67
C    97       67       97
D    34       36       34

In [1494]:
filtered=df["Science"]
print(filtered)

A    94
B    87
C    67
D    36
Name: Science, dtype: int64

In [1495]:
# Filter rows where Math>50
filtered=df["Science"][df["Science"]>50]
print(filtered)

A    94
B    87
C    67
Name: Science, dtype: int64

In [1496]:
filtered=df["Science"][df["Science"]>50] & df["Math"][df["Math"]<25]
print(filtered)

A    False
B    False
C    False
dtype: bool

<ipython-input-1496-07398f26c130>:1: FutureWarning: Operation between non boolean Series with different indexes will no longer return a boolean result in a future version. Cast both Series to object type to maintain the prior behavior.
  filtered=df["Science"][df["Science"]>50] & df["Math"][df["Math"]<25]

df=pd.read_csv('filename/loc,encoding="ISO-8859-1")

encoding="ISO-8859-1 is used,if we face error while uploading

In [1497]:
df=pd.read_csv("https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/titanic.csv")

In [1498]:
df.head(10)# to view rows from first

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
5,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,26.5500,E12,S,1
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0000,1,0,13502,77.9583,D7,S,1
7,1,"Andrews, Mr. Thomas Jr",male,39.0000,0,0,112050,0.0000,A36,S,0
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0000,2,0,11769,51.4792,C101,S,1
9,1,"Artagaveytia, Mr. Ramon",male,71.0000,0,0,PC 17609,49.5042,NaN,C,0

df.head will give you by deafult 5 first values.

if we pass positive value it will show the data upto the value only and if we want negative values it remove that no. of rows from the last

In [1499]:
df.tail(5)# to last rows from first

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,0

In [1500]:
df.shape # Get the number of rows and columns
df.shape[0] # Get the number of rows only
df.shape[1] # Get the number of columns only

11

The .info() method is a quick way to look at the data types, missing values, and data size of a DataFrame. Here, we’re setting the show_counts argument to True, which gives a few over the total non-missing values in each column. We’re also setting memory_usage to True, which shows the total memory usage of the DataFrame elements. When verbose is set to True, it prints the full summary from .info().

In [1501]:
df.info()#information of entire dataset ,non null count, the datatype of each and every column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   name      1309 non-null   object
 2   sex       1309 non-null   object
 3   age       1046 non-null   float64
 4   sibsp     1309 non-null   int64
 5   parch     1309 non-null   int64
 6   ticket    1309 non-null   object
 7   fare      1308 non-null   float64
 8   cabin     295 non-null    object
 9   embarked  1307 non-null   object
 10  survived  1309 non-null   int64
dtypes: float64(2), int64(4), object(5)
memory usage: 112.6+ KB

In [1502]:
df.columns#to know the column names

Index(['pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare',
       'cabin', 'embarked', 'survived'],
      dtype='object')

In [1503]:
df.describe()# descriptive statistics summarizing the central tendency, dispersion, and shape of a dataset's distribution.

,pclass,age,sibsp,parch,fare,survived
count,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,1309.000000
mean,2.294882,29.881135,0.498854,0.385027,33.295479,0.381971
std,0.837836,14.413500,1.041658,0.865560,51.758668,0.486055
min,1.000000,0.166700,0.000000,0.000000,0.000000,0.000000
25%,2.000000,21.000000,0.000000,0.000000,7.895800,0.000000
50%,3.000000,28.000000,0.000000,0.000000,14.454200,0.000000
75%,3.000000,39.000000,1.000000,0.000000,31.275000,1.000000
max,3.000000,80.000000,8.000000,9.000000,512.329200,1.000000

In [1504]:
df["sibsp"].unique()#method identifies and extracts distinct values from a Pandas Series or DataFrame column.

array([0, 1, 2, 3, 4, 5, 8])

In [1505]:
df["embarked"].unique()

array(['S', 'C', nan, 'Q'], dtype=object)

In [1506]:
df["embarked"].value_counts()# in case of values_count it will return the frequency  of non-null and uniques values

embarked
S    914
C    270
Q    123
Name: count, dtype: int64

In [1507]:
df["sibsp"].count()

np.int64(1309)

In [1508]:
df.drop_duplicates()#will remove the dublicate rows but not reflect in my original dataset

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [1509]:
df.drop_duplicates(inplace=True)#inplace is used for removing the dublicate rows but not reflect in my original dataset
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [1510]:
df.isnull().sum()#Checking for missing values in pandas with .isnull()

pclass         0
name           0
sex            0
age          263
sibsp          0
parch          0
ticket         0
fare           1
cabin       1014
embarked       2
survived       0
dtype: int64

Syntax of loc (lable based indexing)

Dataframe.loc[specific rows, specific columns]

In [1511]:
df.loc[1:5,["name","age"]]#only uesd for row sclicing for specific columns

                                              name      age
1                   Allison, Master. Hudson Trevor   0.9167
2                     Allison, Miss. Helen Loraine   2.0000
3             Allison, Mr. Hudson Joshua Creighton  30.0000
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0000
5                              Anderson, Mr. Harry  48.0000

In [1512]:
df.loc[:,["name"]]

                                                 name
0                       Allen, Miss. Elisabeth Walton
1                      Allison, Master. Hudson Trevor
2                        Allison, Miss. Helen Loraine
3                Allison, Mr. Hudson Joshua Creighton
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
...                                               ...
1304                             Zabour, Miss. Hileni
1305                            Zabour, Miss. Thamine
1306                        Zakarian, Mr. Mapriededer
1307                              Zakarian, Mr. Ortin
1308                               Zimmerman, Mr. Leo

[1309 rows x 1 columns]

In [1513]:
df.loc[1:5,"name":"age"]# labled_based sclicing or indexing

                                              name     sex      age
1                   Allison, Master. Hudson Trevor    male   0.9167
2                     Allison, Miss. Helen Loraine  female   2.0000
3             Allison, Mr. Hudson Joshua Creighton    male  30.0000
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0000
5                              Anderson, Mr. Harry    male  48.0000

The iloc function in Python is an index-based function. In this function, we select an integer position instead of selecting rows or columns. It can also work across multiple DataFrame Objects."iloc" method is a valuable tool for selecting rows and columns by an integer

Syntax of iloc

df.iloc[row_index_value, column_index_value]

In [1514]:
df.iloc[:10,1:4]

                                              name     sex      age
0                    Allen, Miss. Elisabeth Walton  female  29.0000
1                   Allison, Master. Hudson Trevor    male   0.9167
2                     Allison, Miss. Helen Loraine  female   2.0000
3             Allison, Mr. Hudson Joshua Creighton    male  30.0000
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0000
5                              Anderson, Mr. Harry    male  48.0000
6                Andrews, Miss. Kornelia Theodosia  female  63.0000
7                           Andrews, Mr. Thomas Jr    male  39.0000
8    Appleton, Mrs. Edward Dale (Charlotte Lamson)  female  53.0000
9                          Artagaveytia, Mr. Ramon    male  71.0000

In [1515]:
df.loc[1:]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
5,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,26.5500,E12,S,1
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

#When should we use loc instead of iloc from a Pandas DataFrame?
To select data based on label-based indexing, it is recommended to use loc. And iloc should be used when there is a need to choose data that is classified via integer-based indexing


#What happens if you use a non-unique label when using loc to select data?
Using loc with a non-unique label will throw a KeyError exception. This is because loc assumes that the labels used for indexing are unique and will return a single row or column. We should use Boolean indexing to select more than one row or column where duplicates exist.

#What happens if you pick rows or columns in a Pandas DataFrame using a negative integer with iloc?
If there is a negative integer used with 'iloc', it will start counting rows and columns from the end of the DataFrame. For example if you want to select the last row in the DataFrame then you can use ‘-1’.

#How are missing values handled when the developer is using loc and iloc functions?
They are simply removed from the selection. If you want to remove missing values you can use fillna() or dropna() function which will either remove or fill missing values with null.

#Where do you use loc and iloc functions?
Both of the functions are used in data analysis and data manipulation tasks. They are used in data filtering, data transformation or in data aggregation.

# Sorting data

To sort a DataFrame by a specific column:

In [1516]:
df.sort_values(by="ticket",ascending=False)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
81,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.000,B22,S,0
82,1,"Crosby, Miss. Harriet R",female,36.0,0,2,WE/P 5735,71.000,B22,S,1
433,2,"Harris, Mr. Walter",male,30.0,0,0,W/C 14208,10.500,NaN,S,0
62,1,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.175,E31,S,0
63,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.175,E31,S,1
...,...,...,...,...,...,...,...,...,...,...,...
291,1,"Taussig, Mrs. Emil (Tillie Mandelbaum)",female,39.0,1,1,110413,79.650,E67,S,1
290,1,"Taussig, Mr. Emil",male,52.0,1,1,110413,79.650,E67,S,0
195,1,"Maioni, Miss. Roberta",female,16.0,0,0,110152,86.500,B79,S,1
67,1,"Cherry, Miss. Gladys",female,30.0,0,0,110152,86.500,B77,S,1
245,1,"Rothes, the Countess. of (Lucy Noel Martha Dye...",female,33.0,0,0,110152,86.500,B77,S,1

You can sort by multiple columns:

In [1517]:
df.sort_values(by=["ticket", "fare"], ascending=[False, False])

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
81,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.000,B22,S,0
82,1,"Crosby, Miss. Harriet R",female,36.0,0,2,WE/P 5735,71.000,B22,S,1
433,2,"Harris, Mr. Walter",male,30.0,0,0,W/C 14208,10.500,NaN,S,0
62,1,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.175,E31,S,0
63,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.175,E31,S,1
...,...,...,...,...,...,...,...,...,...,...,...
290,1,"Taussig, Mr. Emil",male,52.0,1,1,110413,79.650,E67,S,0
291,1,"Taussig, Mrs. Emil (Tillie Mandelbaum)",female,39.0,1,1,110413,79.650,E67,S,1
67,1,"Cherry, Miss. Gladys",female,30.0,0,0,110152,86.500,B77,S,1
195,1,"Maioni, Miss. Roberta",female,16.0,0,0,110152,86.500,B79,S,1
245,1,"Rothes, the Countess. of (Lucy Noel Martha Dye...",female,33.0,0,0,110152,86.500,B77,S,1

In [1518]:
df[df["fare"] > 100] #Filtering data using conditions

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
312,1,"Widener, Mr. George Dunton",male,50.0000,1,1,113503,211.5000,C80,C,0
313,1,"Widener, Mr. Harry Elkins",male,27.0000,0,2,113503,211.5000,C82,C,0
314,1,"Widener, Mrs. George Dunton (Eleanor Elkins)",female,50.0000,1,1,113503,211.5000,C80,C,1
319,1,"Wilson, Miss. Helen Alice",female,31.0000,0,0,16966,134.5000,E39 E41,C,1
322,1,"Young, Miss. Marie Grice",female,36.0000,0,0,PC 17760,135.6333,C32,C,1

In [1519]:
df=pd.read_csv("https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/hr_data.csv")
df

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [1520]:
df["department"].unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

# Conditional slicing (that fits certain conditions)

In [1521]:
#Find the total time spend in the company of managemaent who are getting medium salary
sal=df.groupby("department")
mar=sal.get_group("management")
mar
[mar["salary"]=="medium"]
mar["time_spend_company"][mar["salary"]=="medium"]

60       5
311      4
387      4
539      4
615      4
        ..
14271    5
14522    4
14598    4
14750    4
14826    4
Name: time_spend_company, Length: 225, dtype: int64

In [1522]:
#Find the total time spend
mar["time_spend_company"][mar["salary"]=="medium"].sum()

np.int64(935)

In [1523]:
#count the no.of employee left from the company who are getting low salary in the support dept
sup=sal.get_group("support")
sup
sup['employee_id'][(sup["left"]==1) & (sup["salary"]=="low")].count()

np.int64(389)

In [1524]:
#count the no. of people those who are working on less than 5 project on it IT department
it=sal.get_group("IT")
it
it["number_project"][(it["number_project"])<5].count()

np.int64(876)

In [1525]:
#fetch the employee id those who have woked on minimum 3 project, there salary is high and spend minium 2 years of time from HR dept
hr=sal.get_group("hr")
hr["employee_id"][(hr["number_project"]>=3) & (hr["salary"]=="high")& (hr["time_spend_company"]>=2)]

111       1698
3237     19426
3238     19427
3465     20790
3618     21614
3696     22100
4233     91049
4687     27655
5219     30730
5527     32530
5528     32539
5985     52260
5986     35226
5987     35229
5988     35245
6138      1824
6216     36657
6594     38995
7054     41806
7057     41816
8352     49310
8353     49319
8733     51666
8811     52063
8812     52066
8887     23240
9343     55140
9802     57844
9805     57867
10338    10797
10639    62552
10640    62577
10641    62578
10642    62579
12111    70813
12850    74864
12851    74868
12852    96102
12853    74880
14322    83599
Name: employee_id, dtype: int64

In [1526]:
#count the no. of people having Work_accident in sales deptsal
var = df.groupby("department")
sal = var.get_group("sales")
sal["employee_id"][(sal['department']=="sales") & (sal['Work_accident']==1)].count()

np.int64(587)

In [1527]:
#count the no. of people who is having average working hour in support dept
sal=var.get_group("support")
m=sal['average_montly_hours'].mean()
sal["employee_id"][(sal['average_montly_hours']==200)].count()

np.int64(6)

In [1528]:
 #find the avrage no. of projects people are handling with high salary in the it dept
m=it['number_project'].mean()
it["number_project"][(it["number_project"]==4) & (it["salary"]=="high")].count()

np.int64(21)

In [1529]:
#total no. of project handled by support dept
sup["number_project"].count()

np.int64(2229)

In [1530]:
#Find the max monthy hour working in marketing dept fetch their details
dept = var.get_group("marketing")
m=dept['average_montly_hours'].max()
dept[dept['average_montly_hours']==m]

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
1228,7955,7,310,5,0,1,0,marketing,low

In [1531]:
#average time spend by the ppl in support depa

In [1563]:
df=pd.read_csv("https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/titanic.csv")
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [1564]:
#how many ppl survived in 5b Cabin
df["name"][(df["cabin"]=="B5")&(df["survived"]==1)].count()

np.int64(2)

In [1566]:
#count of female whose age is less than 20 and survived
(df['sex']=='female').sum()

np.int64(466)

In [1569]:
#Total fare paid by embarked S female
df['fare'][(df['sex']=='female')&(df['embarked']=='S')].sum()

np.float64(11447.7378)

In [1570]:
#count of ppl in pclass 3 having only 1 person with them
(df['pclass']==3).sum()

np.int64(709)

In [1572]:
#maximum fare paid in embarked Q
df['fare'][(df['embarked']=='Q')].max()

90.0

#Data Cleaning

In [1538]:

df=pd.read_csv("https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/amazon_fires.csv",encoding='ISO-8859-1')
df

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

#How to rename a column

d={"old_m"="name"}

df.rename(column=d,inplace=True)

In [1539]:
#rename all the column present in the data set
d={'ano':'year','mes': "month","estado": "state",'numero':"Number of files",'encontro':'Date'}
df.rename(columns=d,inplace=True)
df

      year     month      state Number of files      Date
0     1998   Janeiro       Acre         0 Fires  1/1/1998
1     1999   Janeiro       Acre         0 Fires  1/1/1999
2     2000   Janeiro       Acre         0 Fires  1/1/2000
3     2001   Janeiro       Acre         0 Fires  1/1/2001
4     2002   Janeiro       Acre         0 Fires  1/1/2002
...    ...       ...        ...             ...       ...
6449  2012  Dezembro  Tocantins             128  1/1/2012
6450  2013  Dezembro  Tocantins              85  1/1/2013
6451  2014  Dezembro  Tocantins             223  1/1/2014
6452  2015  Dezembro  Tocantins             373  1/1/2015
6453  2016  Dezembro  Tocantins             119  1/1/2016

[6454 rows x 5 columns]

In [1540]:
#drop the year column
df.drop(['year'],axis=1,inplace=True)
df

         month      state Number of files      Date
0      Janeiro       Acre         0 Fires  1/1/1998
1      Janeiro       Acre         0 Fires  1/1/1999
2      Janeiro       Acre         0 Fires  1/1/2000
3      Janeiro       Acre         0 Fires  1/1/2001
4      Janeiro       Acre         0 Fires  1/1/2002
...        ...        ...             ...       ...
6449  Dezembro  Tocantins             128  1/1/2012
6450  Dezembro  Tocantins              85  1/1/2013
6451  Dezembro  Tocantins             223  1/1/2014
6452  Dezembro  Tocantins             373  1/1/2015
6453  Dezembro  Tocantins             119  1/1/2016

[6454 rows x 4 columns]

In [1541]:
df['year']=[i.split('/')[-1] for i in df['Date'] ]
df

         month      state Number of files      Date  year
0      Janeiro       Acre         0 Fires  1/1/1998  1998
1      Janeiro       Acre         0 Fires  1/1/1999  1999
2      Janeiro       Acre         0 Fires  1/1/2000  2000
3      Janeiro       Acre         0 Fires  1/1/2001  2001
4      Janeiro       Acre         0 Fires  1/1/2002  2002
...        ...        ...             ...       ...   ...
6449  Dezembro  Tocantins             128  1/1/2012  2012
6450  Dezembro  Tocantins              85  1/1/2013  2013
6451  Dezembro  Tocantins             223  1/1/2014  2014
6452  Dezembro  Tocantins             373  1/1/2015  2015
6453  Dezembro  Tocantins             119  1/1/2016  2016

[6454 rows x 5 columns]

In [1542]:
df['Number of files'].unique()
for i in df["Number of files"]:
  print(i,type(i))

0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
10 Fires <class 'str'>
0 Fires <class 'str'>
12 Fires <class 'str'>
4 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
12 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
0 Fires <class 'str'>
3 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
5 Fires <class 'str'>
0 Fires <class 'str'>
2 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
2 Fires <class 'str'>
5 Fires <class 'str'>
1 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
11 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
3 Fires <class 'str'>
0 Fires <class 'str'>
2 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
2 Fires <class 'str'>
1 Fires <class 'str'>
2 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
2 Fires <class 'str'>
1 Fires <class 'str'>
nan <class 'float'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
3 Fires <class 'str'>
2 Fires <class 'str'>
1 Fires <class 'str'>
19 Fires <class 'str'>
7 Fires <class 'str'>
3 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
6 Fires <class 'str'>
7 Fires <class 'str'>
2 Fires <class 'str'>
8 Fires <class 'str'>
1 Fires <class 'str'>
0 Fires <class 'str'>
3 Fires <class 'str'>
9 Fires <class 'str'>
3 Fires <class 'str'>
3 Fires <class 'str'>
4 Fires <class 'str'>
1 Fires <class 'str'>
2 Fires <class 'str'>
21 Fires <class 'str'>
10 Fires <class 'str'>
3 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
1 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
5 Fires <class 'str'>
27 Fires <class 'str'>
1 Fires <class 'str'>
4 Fires <class 'str'>
nan <class 'float'>
0 Fires <class 'str'>
1 Fires <class 'str'>
10 Fires <class 'str'>
7 Fires <class 'str'>
8 Fires <class 'str'>
17 Fires <class 'str'>
40 Fires <class 'str'>
87 Fires <class 'str'>
45 Fires <class 'str'>
37 Fires <class 'str'>
1 Fires <class 'str'>
1 Fires <class 'str'>
3 Fires <class 'str'>
39 Fires <class 'str'>
168 Fires <class 'str'>
42 Fires <class 'str'>
nan <class 'float'>
33 Fires <class 'str'>
29 Fires <class 'str'>
41 Fires <class 'str'>
31 Fires <class 'str'>
126 Fires <class 'str'>
93 Fires <class 'str'>
71 Fires <class 'str'>
54 Fires <class 'str'>
60 Fires <class 'str'>
109 Fires <class 'str'>
533 Fires <class 'str'>
457 Fires <class 'str'>
130 Fires <class 'str'>
63 Fires <class 'str'>
136 Fires <class 'str'>
396 Fires <class 'str'>
728 Fires <class 'str'>
1.976 Fires <class 'str'>
645 Fires <class 'str'>
4.198 Fires <class 'str'>
839 Fires <class 'str'>
960 Fires <class 'str'>
445 Fires <class 'str'>
194 Fires <class 'str'>
1.682 Fires <class 'str'>
425 Fires <class 'str'>
739 Fires <class 'str'>
679 Fires <class 'str'>
1.1 Fires <class 'str'>
1.397 Fires <class 'str'>
2.188 Fires <class 'str'>
1.493 Fires <class 'str'>
509 Fires <class 'str'>
209 Fires <class 'str'>
265 Fires <class 'str'>
290 Fires <class 'str'>
1.949 Fires <class 'str'>
3.942 Fires <class 'str'>
1.978 Fires <class 'str'>
4.253 Fires <class 'str'>
2.37 Fires <class 'str'>
2.08 Fires <class 'str'>
1.666 Fires <class 'str'>
1.265 Fires <class 'str'>
2.531 Fires <class 'str'>
1.204 Fires <class 'str'>
1.996 Fires <class 'str'>
2.136 Fires <class 'str'>
2.175 Fires <class 'str'>
2.928 Fires <class 'str'>
3.586 Fires <class 'str'>
3.429 Fires <class 'str'>
44 Fires <class 'str'>
60 Fires <class 'str'>
18 Fires <class 'str'>
137 Fires <class 'str'>
687 Fires <class 'str'>
740 Fires <class 'str'>
461 Fires <class 'str'>
547 Fires <class 'str'>
316 Fires <class 'str'>
203 Fires <class 'str'>
652 Fires <class 'str'>
565 Fires <class 'str'>
292 Fires <class 'str'>
97 Fires <class 'str'>
348 Fires <class 'str'>
258 Fires <class 'str'>
406 Fires <class 'str'>
905 Fires <class 'str'>
509 Fires <class 'str'>
1.508 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
86 Fires <class 'str'>
15 Fires <class 'str'>
nan <class 'float'>
14 Fires <class 'str'>
18 Fires <class 'str'>
7 Fires <class 'str'>
4 Fires <class 'str'>
33 Fires <class 'str'>
39 Fires <class 'str'>
74 Fires <class 'str'>
13 Fires <class 'str'>
79 Fires <class 'str'>
56 Fires <class 'str'>
nan <class 'float'>
46 Fires <class 'str'>
98 Fires <class 'str'>
7 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
1 Fires <class 'str'>
7 Fires <class 'str'>
2 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
0 Fires <class 'str'>
4 Fires <class 'str'>
1 Fires <class 'str'>
3 Fires <class 'str'>
6 Fires <class 'str'>
8 Fires <class 'str'>
6 Fires <class 'str'>
0 <class 'str'>
58 <class 'str'>
11 <class 'str'>
5 <class 'str'>
12 <class 'str'>
150 <class 'str'>
9 <class 'str'>
83 <class 'str'>
29 <class 'str'>
33 <class 'str'>
55 <class 'str'>
104 <class 'str'>
23 <class 'str'>
41 <class 'str'>
36 <class 'str'>
49 <class 'str'>
54 <class 'str'>
81 <class 'str'>
24 <class 'str'>
38 <class 'str'>
38 <class 'str'>
0 <class 'str'>
20 <class 'str'>
16 <class 'str'>
4 <class 'str'>
15 <class 'str'>
33 <class 'str'>
7 <class 'str'>
31 <class 'str'>
14 <class 'str'>
28 <class 'str'>
74 <class 'str'>
32 <class 'str'>
26 <class 'str'>
33 <class 'str'>
41 <class 'str'>
19 <class 'str'>
29 <class 'str'>
46 <class 'str'>
14 <class 'str'>
21 <class 'str'>
0 <class 'str'>
52 <class 'str'>
32 <class 'str'>
0 <class 'str'>
27 <class 'str'>
15 <class 'str'>
16 <class 'str'>
35 <class 'str'>
37 <class 'str'>
7 <class 'str'>
31 <class 'str'>
31 <class 'str'>
70 <class 'str'>
34 <class 'str'>
44 <class 'str'>
31 <class 'str'>
28 <class 'str'>
32 <class 'str'>
9 <class 'str'>
23 <class 'str'>
0 <class 'str'>
4 <class 'str'>
20 <class 'str'>
0 <class 'str'>
6 <class 'str'>
20 <class 'str'>
6 <class 'str'>
1 <class 'str'>
2 <class 'str'>
1 <class 'str'>
18 <class 'str'>
5 <class 'str'>
3 <class 'str'>
17 <class 'str'>
18 <class 'str'>
25 <class 'str'>
16 <class 'str'>
63 <class 'str'>
13 <class 'str'>
7 <class 'str'>
0 <class 'str'>
1 <class 'str'>
1 <class 'str'>
2 <class 'str'>
1 <class 'str'>
1 <class 'str'>
3 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
21 <class 'str'>
2 <class 'str'>
1 <class 'str'>
18 <class 'str'>
4 <class 'str'>
1 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
2 <class 'str'>
4 <class 'str'>
1 <class 'str'>
2 <class 'str'>
2 <class 'str'>
5 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
5 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
1 <class 'str'>
0 <class 'str'>
3 <class 'str'>
0 <class 'str'>
1 <class 'str'>
3 <class 'str'>
4 <class 'str'>
1 <class 'str'>
3 <class 'str'>
2 <class 'str'>
2 <class 'str'>
2 <class 'str'>
1 <class 'str'>
3 <class 'str'>
1 <class 'str'>
0 <class 'str'>
1 <class 'str'>
4 <class 'str'>
0 <class 'str'>
0 <class 'str'>
3 <class 'str'>
3 <class 'str'>
5 <class 'str'>
1 <class 'str'>
14 <class 'str'>
3 <class 'str'>
22 <class 'str'>
5 <class 'str'>
14 <class 'str'>
8 <class 'str'>
5 <class 'str'>
7 <class 'str'>
4 <class 'str'>
2 <class 'str'>
9 <class 'str'>
13 <class 'str'>
5 <class 'str'>
5 <class 'str'>
6 <class 'str'>
4 <class 'str'>
11 <class 'str'>
7 <class 'str'>
18 <class 'str'>
4 <class 'str'>
20 <class 'str'>
4 <class 'str'>
13 <class 'str'>
15 <class 'str'>
30 <class 'str'>
10 <class 'str'>
12 <class 'str'>
17 <class 'str'>
32 <class 'str'>
6 <class 'str'>
18 <class 'str'>
30 <class 'str'>
16 <class 'str'>
23 <class 'str'>
28 <class 'str'>
25 <class 'str'>
7 <class 'str'>
40 <class 'str'>
74 <class 'str'>
14 <class 'str'>
19 <class 'str'>
15 <class 'str'>
2 <class 'str'>
22 <class 'str'>
nan <class 'float'>
17 <class 'str'>
28 <class 'str'>
25 <class 'str'>
12 <class 'str'>
15 <class 'str'>
37 <class 'str'>
55 <class 'str'>
31 <class 'str'>
23 <class 'str'>
95 <class 'str'>
10 <class 'str'>
14 <class 'str'>
162 <class 'str'>
76 <class 'str'>
10 <class 'str'>
32 <class 'str'>
12 <class 'str'>
2 <class 'str'>
30 <class 'str'>
95 <class 'str'>
43 <class 'str'>
71 <class 'str'>
16 <class 'str'>
30 <class 'str'>
33 <class 'str'>
34 <class 'str'>
55 <class 'str'>
45 <class 'str'>
50 <class 'str'>
59 <class 'str'>
42 <class 'str'>
24 <class 'str'>
136 <class 'str'>
155 <class 'str'>
0 <class 'str'>
0 <class 'str'>
2 <class 'str'>
0 <class 'str'>
7 <class 'str'>
31 <class 'str'>
38 <class 'str'>
109 <class 'str'>
6 <class 'str'>
0 <class 'str'>
2 <class 'str'>
4 <class 'str'>
2 <class 'str'>
0 <class 'str'>
30 <class 'str'>
3 <class 'str'>
10 <class 'str'>
14 <class 'str'>
19 <class 'str'>
2 <class 'str'>
0 <class 'str'>
1 <class 'str'>
0 <class 'str'>
0 <class 'str'>
2 <class 'str'>
0 <class 'str'>
2 <class 'str'>
1 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
3 <class 'str'>
5 <class 'str'>
0 <class 'str'>
2 <class 'str'>
1 <class 'str'>
1 <class 'str'>
0 <class 'str'>
0 <class 'str'>
2 <class 'str'>
0 <class 'str'>
nan <class 'float'>
0 <class 'str'>
1 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
1 <class 'str'>
1 <class 'str'>
2 <class 'str'>
0 <class 'str'>
1 <class 'str'>
0 <class 'str'>
1 <class 'str'>
2 <class 'str'>
5 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
2 <class 'str'>
nan <class 'float'>
2 <class 'str'>
0 <class 'str'>
2 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
3 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
3 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
2 <class 'str'>
2 <class 'str'>
2 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
1 <class 'str'>
1 <class 'str'>
0 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
5 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
1 <class 'str'>
0 <class 'str'>
0 <class 'str'>
7 <class 'str'>
1 <class 'str'>
0 <class 'str'>
3 <class 'str'>
2 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
1 <class 'str'>
1 <class 'str'>
0 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
4 <class 'str'>
2 <class 'str'>
5 <class 'str'>
3 <class 'str'>
nan <class 'float'>
4 <class 'str'>
5 <class 'str'>
1 <class 'str'>
3 <class 'str'>
1 <class 'str'>
0 <class 'str'>
3 <class 'str'>
12 <class 'str'>
18 <class 'str'>
14 <class 'str'>
9 <class 'str'>
4 <class 'str'>
11 <class 'str'>
5 <class 'str'>
4 <class 'str'>
20 <class 'str'>
1 <class 'str'>
16 <class 'str'>
19 <class 'str'>
9 <class 'str'>
18 <class 'str'>
40 <class 'str'>
37 <class 'str'>
33 <class 'str'>
20 <class 'str'>
4 <class 'str'>
19 <class 'str'>
nan <class 'float'>
73 <class 'str'>
88 <class 'str'>
67 <class 'str'>
97 <class 'str'>
112 <class 'str'>
61 <class 'str'>
83 <class 'str'>
nan <class 'float'>
63 <class 'str'>
128 <class 'str'>
168 <class 'str'>
85 <class 'str'>
137 <class 'str'>
192 <class 'str'>
142 <class 'str'>
95 <class 'str'>
42 <class 'str'>
25 <class 'str'>
42 <class 'str'>
nan <class 'float'>
557 <class 'str'>
355 <class 'str'>
412 <class 'str'>
335 <class 'str'>
405 <class 'str'>
162 <class 'str'>
395 <class 'str'>
765 <class 'str'>
265 <class 'str'>
304 <class 'str'>
475 <class 'str'>
385 <class 'str'>
480 <class 'str'>
827 <class 'str'>
793 <class 'str'>
nan <class 'float'>
131 <class 'str'>
26 <class 'str'>
157 <class 'str'>
406 <class 'str'>
1.096 <class 'str'>
750 <class 'str'>
949 <class 'str'>
685 <class 'str'>
207 <class 'str'>
198 <class 'str'>
266 <class 'str'>
1.019 <class 'str'>
339 <class 'str'>
282 <class 'str'>
969 <class 'str'>
341 <class 'str'>
484 <class 'str'>
1.3 <class 'str'>
1.161 <class 'str'>
858 <class 'str'>
84 <class 'str'>
41 <class 'str'>
30 <class 'str'>
593 <class 'str'>
200 <class 'str'>
411 <class 'str'>
nan <class 'float'>
38 <class 'str'>
74 <class 'str'>
14 <class 'str'>
32 <class 'str'>
123 <class 'str'>
43 <class 'str'>
360 <class 'str'>
422 <class 'str'>
148 <class 'str'>
354 <class 'str'>
269 <class 'str'>
491 <class 'str'>
0 <class 'str'>
3 <class 'str'>
7 <class 'str'>
3 <class 'str'>
17 <class 'str'>
158 <class 'str'>
123 <class 'str'>
44 <class 'str'>
20 <class 'str'>
37 <class 'str'>
16 <class 'str'>
9 <class 'str'>
82 <class 'str'>
53 <class 'str'>
6 <class 'str'>
37 <class 'str'>
46 <class 'str'>
35 <class 'str'>
770 <class 'str'>
65 <class 'str'>
0 <class 'str'>
43 <class 'str'>
62 <class 'str'>
8 <class 'str'>
2 <class 'str'>
62 <class 'str'>
92 <class 'str'>
6 <class 'str'>
10 <class 'str'>
92 <class 'str'>
32 <class 'str'>
3 <class 'str'>
81 <class 'str'>
30 <class 'str'>
25 <class 'str'>
16 <class 'str'>
49 <class 'str'>
107 <class 'str'>
275 <class 'str'>
52 <class 'str'>
0 <class 'str'>
7 <class 'str'>
69 <class 'str'>
6 <class 'str'>
5 <class 'str'>
64 <class 'str'>
6 <class 'str'>
12 <class 'str'>
20 <class 'str'>
6 <class 'str'>
nan <class 'float'>
11 <class 'str'>
116 <class 'str'>
nan <class 'float'>
17 <class 'str'>
49 <class 'str'>
50 <class 'str'>
46 <class 'str'>
140 <class 'str'>
45 <class 'str'>
0 <class 'str'>
2 <class 'str'>
18 <class 'str'>
1 <class 'str'>
2 <class 'str'>
11 <class 'str'>
4 <class 'str'>
5 <class 'str'>
5 <class 'str'>
0 <class 'str'>
13 <class 'str'>
1 <class 'str'>
11 <class 'str'>
nan <class 'float'>
3 <class 'str'>
nan <class 'float'>
25 <class 'str'>
24 <class 'str'>
22 <class 'str'>
20 <class 'str'>
0 <class 'str'>
0 <class 'str'>
51 <class 'str'>
0 <class 'str'>
8 <class 'str'>
2 <class 'str'>
0 <class 'str'>
8 <class 'str'>
4 <class 'str'>
0 <class 'str'>
1 <class 'str'>
3 <class 'str'>
13 <class 'str'>
6 <class 'str'>
12 <class 'str'>
19 <class 'str'>
12 <class 'str'>
10 <class 'str'>
30 <class 'str'>
40 <class 'str'>
2 <class 'str'>
7 <class 'str'>
6 <class 'str'>
5 <class 'str'>
5 <class 'str'>
3 <class 'str'>
12 <class 'str'>
78 <class 'str'>
9 <class 'str'>
23 <class 'str'>
7 <class 'str'>
13 <class 'str'>
9 <class 'str'>
22 <class 'str'>
45 <class 'str'>
56 <class 'str'>
74 <class 'str'>
33 <class 'str'>
90 <class 'str'>
119 <class 'str'>
71 <class 'str'>
11 <class 'str'>
39 <class 'str'>
9 <class 'str'>
146 <class 'str'>
180 <class 'str'>
177 <class 'str'>
676 <class 'str'>
123 <class 'str'>
116 <class 'str'>
108 <class 'str'>
199 <class 'str'>
640 <class 'str'>
271 <class 'str'>
234 <class 'str'>
248 <class 'str'>
202 <class 'str'>
356 <class 'str'>
1.137 <class 'str'>
1.975 <class 'str'>
321 <class 'str'>
259 <class 'str'>
180 <class 'str'>
501 <class 'str'>
741 <class 'str'>
1.867 <class 'str'>
1.207 <class 'str'>
2.316 <class 'str'>
1.422 <class 'str'>
2.241 <class 'str'>
861 <class 'str'>
1.321 <class 'str'>
3.727 <class 'str'>
1.243 <class 'str'>
3.011 <class 'str'>
1.276 <class 'str'>
3.852 <class 'str'>
4.564 <class 'str'>
3.611 <class 'str'>
6.316 <class 'str'>
267 <class 'str'>
216 <class 'str'>
189 <class 'str'>
166 <class 'str'>
928 <class 'str'>
1.401 <class 'str'>
911 <class 'str'>
2.812 <class 'str'>
2.218 <class 'str'>
1.36 <class 'str'>
998 <class 'str'>
3.091 <class 'str'>
2.781 <class 'str'>
1.295 <class 'str'>
2.392 <class 'str'>
1.739 <class 'str'>
3.057 <class 'str'>
5.882 <class 'str'>
3.119 <class 'str'>
4.033 <class 'str'>
83 <class 'str'>
479 <class 'str'>
145 <class 'str'>
332 <class 'str'>
695 <class 'str'>
725 <class 'str'>
710 <class 'str'>
545 <class 'str'>
721 <class 'str'>
215 <class 'str'>
632 <class 'str'>
2.189 <class 'str'>
889 <class 'str'>
694 <class 'str'>
1.238 <class 'str'>
1.202 <class 'str'>
952 <class 'str'>
2.494 <class 'str'>
2.105 <class 'str'>
1.581 <class 'str'>
6 <class 'str'>
32 <class 'str'>
27 <class 'str'>
244 <class 'str'>
259 <class 'str'>
169 <class 'str'>
209 <class 'str'>
261 <class 'str'>
59 <class 'str'>
90 <class 'str'>
39 <class 'str'>
973 <class 'str'>
354 <class 'str'>
399 <class 'str'>
682 <class 'str'>
220 <class 'str'>
nan <class 'float'>
1.054 <class 'str'>
591 <class 'str'>
552 <class 'str'>
196 <class 'str'>
2 <class 'str'>
60 <class 'str'>
22 <class 'str'>
44 <class 'str'>
147 <class 'str'>
53 <class 'str'>
17 <class 'str'>
23 <class 'str'>
7 <class 'str'>
0 <class 'str'>
102 <class 'str'>
123 <class 'str'>
121 <class 'str'>
80 <class 'str'>
236 <class 'str'>
293 <class 'str'>
565 <class 'str'>
133 <class 'str'>
0 <class 'str'>
114 <class 'str'>
31 <class 'str'>
24 <class 'str'>
125 <class 'str'>
439 <class 'str'>
158 <class 'str'>
303 <class 'str'>
225 <class 'str'>
373 <class 'str'>
314 <class 'str'>
177 <class 'str'>
297 <class 'str'>
101 <class 'str'>
179 <class 'str'>
125 <class 'str'>
132 <class 'str'>
256 <class 'str'>
285 <class 'str'>
154 <class 'str'>
0 <class 'str'>
157 <class 'str'>
32 <class 'str'>
101 <class 'str'>
204 <class 'str'>
223 <class 'str'>
122 <class 'str'>
143 <class 'str'>
277 <class 'str'>
113 <class 'str'>
235 <class 'str'>
117 <class 'str'>
206 <class 'str'>
156 <class 'str'>
200 <class 'str'>
231 <class 'str'>
107 <class 'str'>
143 <class 'str'>
418 <class 'str'>
100 <class 'str'>
0 <class 'str'>
83 <class 'str'>
65 <class 'str'>
4 <class 'str'>
146 <class 'str'>
274 <class 'str'>
115 <class 'str'>
158 <class 'str'>
199 <class 'str'>
141 <class 'str'>
135 <class 'str'>
249 <class 'str'>
156 <class 'str'>
90 <class 'str'>
404 <class 'str'>
363 <class 'str'>
148 <class 'str'>
229 <class 'str'>
281 <class 'str'>
163 <class 'str'>
0 <class 'str'>
55 <class 'str'>
23 <class 'str'>
26 <class 'str'>
110 <class 'str'>
376 <class 'str'>
89 <class 'str'>
76 <class 'str'>
60 <class 'str'>
64 <class 'str'>
151 <class 'str'>
40 <class 'str'>
103 <class 'str'>
149 <class 'str'>
396 <class 'str'>
108 <class 'str'>
183 <class 'str'>
190 <class 'str'>
nan <class 'float'>
94 <class 'str'>
0 <class 'str'>
76 <class 'str'>
71 <class 'str'>
nan <class 'float'>
166 <class 'str'>
106 <class 'str'>
124 <class 'str'>
120 <class 'str'>
43 <class 'str'>
161 <class 'str'>
56 <class 'str'>
34 <class 'str'>
198 <class 'str'>
189 <class 'str'>
326 <class 'str'>
141 <class 'str'>
224 <class 'str'>
144 <class 'str'>
259 <class 'str'>
121 <class 'str'>
55 <class 'str'>
64 <class 'str'>
178 <class 'str'>
98 <class 'str'>
118 <class 'str'>
140 <class 'str'>
289 <class 'str'>
211 <class 'str'>
68 <class 'str'>
270 <class 'str'>
72 <class 'str'>
92 <class 'str'>
192 <class 'str'>
345 <class 'str'>
385 <class 'str'>
208 <class 'str'>
243 <class 'str'>
242 <class 'str'>
416 <class 'str'>
329 <class 'str'>
219 <class 'str'>
107 <class 'str'>
202 <class 'str'>
248 <class 'str'>
nan <class 'float'>
261 <class 'str'>
310 <class 'str'>
269 <class 'str'>
229 <class 'str'>
811 <class 'str'>
271 <class 'str'>
321 <class 'str'>
519 <class 'str'>

In [1543]:
df["Number of files"] = df["Number of files"].fillna("none")
for i in df["Number of files"]:
  print(i,type(i))
df['Number of files']=[i.split()[0] for i in df['Number of files']]
df

0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
10 Fires <class 'str'>
0 Fires <class 'str'>
12 Fires <class 'str'>
4 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
12 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
0 Fires <class 'str'>
3 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
5 Fires <class 'str'>
0 Fires <class 'str'>
2 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
2 Fires <class 'str'>
5 Fires <class 'str'>
1 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
11 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
3 Fires <class 'str'>
0 Fires <class 'str'>
2 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
2 Fires <class 'str'>
1 Fires <class 'str'>
2 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
2 Fires <class 'str'>
1 Fires <class 'str'>
none <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
3 Fires <class 'str'>
2 Fires <class 'str'>
1 Fires <class 'str'>
19 Fires <class 'str'>
7 Fires <class 'str'>
3 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
6 Fires <class 'str'>
7 Fires <class 'str'>
2 Fires <class 'str'>
8 Fires <class 'str'>
1 Fires <class 'str'>
0 Fires <class 'str'>
3 Fires <class 'str'>
9 Fires <class 'str'>
3 Fires <class 'str'>
3 Fires <class 'str'>
4 Fires <class 'str'>
1 Fires <class 'str'>
2 Fires <class 'str'>
21 Fires <class 'str'>
10 Fires <class 'str'>
3 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
1 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
5 Fires <class 'str'>
27 Fires <class 'str'>
1 Fires <class 'str'>
4 Fires <class 'str'>
none <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
10 Fires <class 'str'>
7 Fires <class 'str'>
8 Fires <class 'str'>
17 Fires <class 'str'>
40 Fires <class 'str'>
87 Fires <class 'str'>
45 Fires <class 'str'>
37 Fires <class 'str'>
1 Fires <class 'str'>
1 Fires <class 'str'>
3 Fires <class 'str'>
39 Fires <class 'str'>
168 Fires <class 'str'>
42 Fires <class 'str'>
none <class 'str'>
33 Fires <class 'str'>
29 Fires <class 'str'>
41 Fires <class 'str'>
31 Fires <class 'str'>
126 Fires <class 'str'>
93 Fires <class 'str'>
71 Fires <class 'str'>
54 Fires <class 'str'>
60 Fires <class 'str'>
109 Fires <class 'str'>
533 Fires <class 'str'>
457 Fires <class 'str'>
130 Fires <class 'str'>
63 Fires <class 'str'>
136 Fires <class 'str'>
396 Fires <class 'str'>
728 Fires <class 'str'>
1.976 Fires <class 'str'>
645 Fires <class 'str'>
4.198 Fires <class 'str'>
839 Fires <class 'str'>
960 Fires <class 'str'>
445 Fires <class 'str'>
194 Fires <class 'str'>
1.682 Fires <class 'str'>
425 Fires <class 'str'>
739 Fires <class 'str'>
679 Fires <class 'str'>
1.1 Fires <class 'str'>
1.397 Fires <class 'str'>
2.188 Fires <class 'str'>
1.493 Fires <class 'str'>
509 Fires <class 'str'>
209 Fires <class 'str'>
265 Fires <class 'str'>
290 Fires <class 'str'>
1.949 Fires <class 'str'>
3.942 Fires <class 'str'>
1.978 Fires <class 'str'>
4.253 Fires <class 'str'>
2.37 Fires <class 'str'>
2.08 Fires <class 'str'>
1.666 Fires <class 'str'>
1.265 Fires <class 'str'>
2.531 Fires <class 'str'>
1.204 Fires <class 'str'>
1.996 Fires <class 'str'>
2.136 Fires <class 'str'>
2.175 Fires <class 'str'>
2.928 Fires <class 'str'>
3.586 Fires <class 'str'>
3.429 Fires <class 'str'>
44 Fires <class 'str'>
60 Fires <class 'str'>
18 Fires <class 'str'>
137 Fires <class 'str'>
687 Fires <class 'str'>
740 Fires <class 'str'>
461 Fires <class 'str'>
547 Fires <class 'str'>
316 Fires <class 'str'>
203 Fires <class 'str'>
652 Fires <class 'str'>
565 Fires <class 'str'>
292 Fires <class 'str'>
97 Fires <class 'str'>
348 Fires <class 'str'>
258 Fires <class 'str'>
406 Fires <class 'str'>
905 Fires <class 'str'>
509 Fires <class 'str'>
1.508 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
86 Fires <class 'str'>
15 Fires <class 'str'>
none <class 'str'>
14 Fires <class 'str'>
18 Fires <class 'str'>
7 Fires <class 'str'>
4 Fires <class 'str'>
33 Fires <class 'str'>
39 Fires <class 'str'>
74 Fires <class 'str'>
13 Fires <class 'str'>
79 Fires <class 'str'>
56 Fires <class 'str'>
none <class 'str'>
46 Fires <class 'str'>
98 Fires <class 'str'>
7 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
1 Fires <class 'str'>
7 Fires <class 'str'>
2 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
0 Fires <class 'str'>
1 Fires <class 'str'>
0 Fires <class 'str'>
4 Fires <class 'str'>
1 Fires <class 'str'>
3 Fires <class 'str'>
6 Fires <class 'str'>
8 Fires <class 'str'>
6 Fires <class 'str'>
0 <class 'str'>
58 <class 'str'>
11 <class 'str'>
5 <class 'str'>
12 <class 'str'>
150 <class 'str'>
9 <class 'str'>
83 <class 'str'>
29 <class 'str'>
33 <class 'str'>
55 <class 'str'>
104 <class 'str'>
23 <class 'str'>
41 <class 'str'>
36 <class 'str'>
49 <class 'str'>
54 <class 'str'>
81 <class 'str'>
24 <class 'str'>
38 <class 'str'>
38 <class 'str'>
0 <class 'str'>
20 <class 'str'>
16 <class 'str'>
4 <class 'str'>
15 <class 'str'>
33 <class 'str'>
7 <class 'str'>
31 <class 'str'>
14 <class 'str'>
28 <class 'str'>
74 <class 'str'>
32 <class 'str'>
26 <class 'str'>
33 <class 'str'>
41 <class 'str'>
19 <class 'str'>
29 <class 'str'>
46 <class 'str'>
14 <class 'str'>
21 <class 'str'>
0 <class 'str'>
52 <class 'str'>
32 <class 'str'>
0 <class 'str'>
27 <class 'str'>
15 <class 'str'>
16 <class 'str'>
35 <class 'str'>
37 <class 'str'>
7 <class 'str'>
31 <class 'str'>
31 <class 'str'>
70 <class 'str'>
34 <class 'str'>
44 <class 'str'>
31 <class 'str'>
28 <class 'str'>
32 <class 'str'>
9 <class 'str'>
23 <class 'str'>
0 <class 'str'>
4 <class 'str'>
20 <class 'str'>
0 <class 'str'>
6 <class 'str'>
20 <class 'str'>
6 <class 'str'>
1 <class 'str'>
2 <class 'str'>
1 <class 'str'>
18 <class 'str'>
5 <class 'str'>
3 <class 'str'>
17 <class 'str'>
18 <class 'str'>
25 <class 'str'>
16 <class 'str'>
63 <class 'str'>
13 <class 'str'>
7 <class 'str'>
0 <class 'str'>
1 <class 'str'>
1 <class 'str'>
2 <class 'str'>
1 <class 'str'>
1 <class 'str'>
3 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
21 <class 'str'>
2 <class 'str'>
1 <class 'str'>
18 <class 'str'>
4 <class 'str'>
1 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
2 <class 'str'>
4 <class 'str'>
1 <class 'str'>
2 <class 'str'>
2 <class 'str'>
5 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
5 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
1 <class 'str'>
0 <class 'str'>
3 <class 'str'>
0 <class 'str'>
1 <class 'str'>
3 <class 'str'>
4 <class 'str'>
1 <class 'str'>
3 <class 'str'>
2 <class 'str'>
2 <class 'str'>
2 <class 'str'>
1 <class 'str'>
3 <class 'str'>
1 <class 'str'>
0 <class 'str'>
1 <class 'str'>
4 <class 'str'>
0 <class 'str'>
0 <class 'str'>
3 <class 'str'>
3 <class 'str'>
5 <class 'str'>
1 <class 'str'>
14 <class 'str'>
3 <class 'str'>
22 <class 'str'>
5 <class 'str'>
14 <class 'str'>
8 <class 'str'>
5 <class 'str'>
7 <class 'str'>
4 <class 'str'>
2 <class 'str'>
9 <class 'str'>
13 <class 'str'>
5 <class 'str'>
5 <class 'str'>
6 <class 'str'>
4 <class 'str'>
11 <class 'str'>
7 <class 'str'>
18 <class 'str'>
4 <class 'str'>
20 <class 'str'>
4 <class 'str'>
13 <class 'str'>
15 <class 'str'>
30 <class 'str'>
10 <class 'str'>
12 <class 'str'>
17 <class 'str'>
32 <class 'str'>
6 <class 'str'>
18 <class 'str'>
30 <class 'str'>
16 <class 'str'>
23 <class 'str'>
28 <class 'str'>
25 <class 'str'>
7 <class 'str'>
40 <class 'str'>
74 <class 'str'>
14 <class 'str'>
19 <class 'str'>
15 <class 'str'>
2 <class 'str'>
22 <class 'str'>
none <class 'str'>
17 <class 'str'>
28 <class 'str'>
25 <class 'str'>
12 <class 'str'>
15 <class 'str'>
37 <class 'str'>
55 <class 'str'>
31 <class 'str'>
23 <class 'str'>
95 <class 'str'>
10 <class 'str'>
14 <class 'str'>
162 <class 'str'>
76 <class 'str'>
10 <class 'str'>
32 <class 'str'>
12 <class 'str'>
2 <class 'str'>
30 <class 'str'>
95 <class 'str'>
43 <class 'str'>
71 <class 'str'>
16 <class 'str'>
30 <class 'str'>
33 <class 'str'>
34 <class 'str'>
55 <class 'str'>
45 <class 'str'>
50 <class 'str'>
59 <class 'str'>
42 <class 'str'>
24 <class 'str'>
136 <class 'str'>
155 <class 'str'>
0 <class 'str'>
0 <class 'str'>
2 <class 'str'>
0 <class 'str'>
7 <class 'str'>
31 <class 'str'>
38 <class 'str'>
109 <class 'str'>
6 <class 'str'>
0 <class 'str'>
2 <class 'str'>
4 <class 'str'>
2 <class 'str'>
0 <class 'str'>
30 <class 'str'>
3 <class 'str'>
10 <class 'str'>
14 <class 'str'>
19 <class 'str'>
2 <class 'str'>
0 <class 'str'>
1 <class 'str'>
0 <class 'str'>
0 <class 'str'>
2 <class 'str'>
0 <class 'str'>
2 <class 'str'>
1 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
3 <class 'str'>
5 <class 'str'>
0 <class 'str'>
2 <class 'str'>
1 <class 'str'>
1 <class 'str'>
0 <class 'str'>
0 <class 'str'>
2 <class 'str'>
0 <class 'str'>
none <class 'str'>
0 <class 'str'>
1 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
1 <class 'str'>
1 <class 'str'>
2 <class 'str'>
0 <class 'str'>
1 <class 'str'>
0 <class 'str'>
1 <class 'str'>
2 <class 'str'>
5 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
2 <class 'str'>
none <class 'str'>
2 <class 'str'>
0 <class 'str'>
2 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
3 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
3 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
2 <class 'str'>
2 <class 'str'>
2 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
1 <class 'str'>
1 <class 'str'>
0 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
5 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
1 <class 'str'>
0 <class 'str'>
0 <class 'str'>
7 <class 'str'>
1 <class 'str'>
0 <class 'str'>
3 <class 'str'>
2 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
1 <class 'str'>
1 <class 'str'>
0 <class 'str'>
2 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
0 <class 'str'>
4 <class 'str'>
2 <class 'str'>
5 <class 'str'>
3 <class 'str'>
none <class 'str'>
4 <class 'str'>
5 <class 'str'>
1 <class 'str'>
3 <class 'str'>
1 <class 'str'>
0 <class 'str'>
3 <class 'str'>
12 <class 'str'>
18 <class 'str'>
14 <class 'str'>
9 <class 'str'>
4 <class 'str'>
11 <class 'str'>
5 <class 'str'>
4 <class 'str'>
20 <class 'str'>
1 <class 'str'>
16 <class 'str'>
19 <class 'str'>
9 <class 'str'>
18 <class 'str'>
40 <class 'str'>
37 <class 'str'>
33 <class 'str'>
20 <class 'str'>
4 <class 'str'>
19 <class 'str'>
none <class 'str'>
73 <class 'str'>
88 <class 'str'>
67 <class 'str'>
97 <class 'str'>
112 <class 'str'>
61 <class 'str'>
83 <class 'str'>
none <class 'str'>
63 <class 'str'>
128 <class 'str'>
168 <class 'str'>
85 <class 'str'>
137 <class 'str'>
192 <class 'str'>
142 <class 'str'>
95 <class 'str'>
42 <class 'str'>
25 <class 'str'>
42 <class 'str'>
none <class 'str'>
557 <class 'str'>
355 <class 'str'>
412 <class 'str'>
335 <class 'str'>
405 <class 'str'>
162 <class 'str'>
395 <class 'str'>
765 <class 'str'>
265 <class 'str'>
304 <class 'str'>
475 <class 'str'>
385 <class 'str'>
480 <class 'str'>
827 <class 'str'>
793 <class 'str'>
none <class 'str'>
131 <class 'str'>
26 <class 'str'>
157 <class 'str'>
406 <class 'str'>
1.096 <class 'str'>
750 <class 'str'>
949 <class 'str'>
685 <class 'str'>
207 <class 'str'>
198 <class 'str'>
266 <class 'str'>
1.019 <class 'str'>
339 <class 'str'>
282 <class 'str'>
969 <class 'str'>
341 <class 'str'>
484 <class 'str'>
1.3 <class 'str'>
1.161 <class 'str'>
858 <class 'str'>
84 <class 'str'>
41 <class 'str'>
30 <class 'str'>
593 <class 'str'>
200 <class 'str'>
411 <class 'str'>
none <class 'str'>
38 <class 'str'>
74 <class 'str'>
14 <class 'str'>
32 <class 'str'>
123 <class 'str'>
43 <class 'str'>
360 <class 'str'>
422 <class 'str'>
148 <class 'str'>
354 <class 'str'>
269 <class 'str'>
491 <class 'str'>
0 <class 'str'>
3 <class 'str'>
7 <class 'str'>
3 <class 'str'>
17 <class 'str'>
158 <class 'str'>
123 <class 'str'>
44 <class 'str'>
20 <class 'str'>
37 <class 'str'>
16 <class 'str'>
9 <class 'str'>
82 <class 'str'>
53 <class 'str'>
6 <class 'str'>
37 <class 'str'>
46 <class 'str'>
35 <class 'str'>
770 <class 'str'>
65 <class 'str'>
0 <class 'str'>
43 <class 'str'>
62 <class 'str'>
8 <class 'str'>
2 <class 'str'>
62 <class 'str'>
92 <class 'str'>
6 <class 'str'>
10 <class 'str'>
92 <class 'str'>
32 <class 'str'>
3 <class 'str'>
81 <class 'str'>
30 <class 'str'>
25 <class 'str'>
16 <class 'str'>
49 <class 'str'>
107 <class 'str'>
275 <class 'str'>
52 <class 'str'>
0 <class 'str'>
7 <class 'str'>
69 <class 'str'>
6 <class 'str'>
5 <class 'str'>
64 <class 'str'>
6 <class 'str'>
12 <class 'str'>
20 <class 'str'>
6 <class 'str'>
none <class 'str'>
11 <class 'str'>
116 <class 'str'>
none <class 'str'>
17 <class 'str'>
49 <class 'str'>
50 <class 'str'>
46 <class 'str'>
140 <class 'str'>
45 <class 'str'>
0 <class 'str'>
2 <class 'str'>
18 <class 'str'>
1 <class 'str'>
2 <class 'str'>
11 <class 'str'>
4 <class 'str'>
5 <class 'str'>
5 <class 'str'>
0 <class 'str'>
13 <class 'str'>
1 <class 'str'>
11 <class 'str'>
none <class 'str'>
3 <class 'str'>
none <class 'str'>
25 <class 'str'>
24 <class 'str'>
22 <class 'str'>
20 <class 'str'>
0 <class 'str'>
0 <class 'str'>
51 <class 'str'>
0 <class 'str'>
8 <class 'str'>
2 <class 'str'>
0 <class 'str'>
8 <class 'str'>
4 <class 'str'>
0 <class 'str'>
1 <class 'str'>
3 <class 'str'>
13 <class 'str'>
6 <class 'str'>
12 <class 'str'>
19 <class 'str'>
12 <class 'str'>
10 <class 'str'>
30 <class 'str'>
40 <class 'str'>
2 <class 'str'>
7 <class 'str'>
6 <class 'str'>
5 <class 'str'>
5 <class 'str'>
3 <class 'str'>
12 <class 'str'>
78 <class 'str'>
9 <class 'str'>
23 <class 'str'>
7 <class 'str'>
13 <class 'str'>
9 <class 'str'>
22 <class 'str'>
45 <class 'str'>
56 <class 'str'>
74 <class 'str'>
33 <class 'str'>
90 <class 'str'>
119 <class 'str'>
71 <class 'str'>
11 <class 'str'>
39 <class 'str'>
9 <class 'str'>
146 <class 'str'>
180 <class 'str'>
177 <class 'str'>
676 <class 'str'>
123 <class 'str'>
116 <class 'str'>
108 <class 'str'>
199 <class 'str'>
640 <class 'str'>
271 <class 'str'>
234 <class 'str'>
248 <class 'str'>
202 <class 'str'>
356 <class 'str'>
1.137 <class 'str'>
1.975 <class 'str'>
321 <class 'str'>
259 <class 'str'>
180 <class 'str'>
501 <class 'str'>
741 <class 'str'>
1.867 <class 'str'>
1.207 <class 'str'>
2.316 <class 'str'>
1.422 <class 'str'>
2.241 <class 'str'>
861 <class 'str'>
1.321 <class 'str'>
3.727 <class 'str'>
1.243 <class 'str'>
3.011 <class 'str'>
1.276 <class 'str'>
3.852 <class 'str'>
4.564 <class 'str'>
3.611 <class 'str'>
6.316 <class 'str'>
267 <class 'str'>
216 <class 'str'>
189 <class 'str'>
166 <class 'str'>
928 <class 'str'>
1.401 <class 'str'>
911 <class 'str'>
2.812 <class 'str'>
2.218 <class 'str'>
1.36 <class 'str'>
998 <class 'str'>
3.091 <class 'str'>
2.781 <class 'str'>
1.295 <class 'str'>
2.392 <class 'str'>
1.739 <class 'str'>
3.057 <class 'str'>
5.882 <class 'str'>
3.119 <class 'str'>
4.033 <class 'str'>
83 <class 'str'>
479 <class 'str'>
145 <class 'str'>
332 <class 'str'>
695 <class 'str'>
725 <class 'str'>
710 <class 'str'>
545 <class 'str'>
721 <class 'str'>
215 <class 'str'>
632 <class 'str'>
2.189 <class 'str'>
889 <class 'str'>
694 <class 'str'>
1.238 <class 'str'>
1.202 <class 'str'>
952 <class 'str'>
2.494 <class 'str'>
2.105 <class 'str'>
1.581 <class 'str'>
6 <class 'str'>
32 <class 'str'>
27 <class 'str'>
244 <class 'str'>
259 <class 'str'>
169 <class 'str'>
209 <class 'str'>
261 <class 'str'>
59 <class 'str'>
90 <class 'str'>
39 <class 'str'>
973 <class 'str'>
354 <class 'str'>
399 <class 'str'>
682 <class 'str'>
220 <class 'str'>
none <class 'str'>
1.054 <class 'str'>
591 <class 'str'>
552 <class 'str'>
196 <class 'str'>
2 <class 'str'>
60 <class 'str'>
22 <class 'str'>
44 <class 'str'>
147 <class 'str'>
53 <class 'str'>
17 <class 'str'>
23 <class 'str'>
7 <class 'str'>
0 <class 'str'>
102 <class 'str'>
123 <class 'str'>
121 <class 'str'>
80 <class 'str'>
236 <class 'str'>
293 <class 'str'>
565 <class 'str'>
133 <class 'str'>
0 <class 'str'>
114 <class 'str'>
31 <class 'str'>
24 <class 'str'>
125 <class 'str'>
439 <class 'str'>
158 <class 'str'>
303 <class 'str'>
225 <class 'str'>
373 <class 'str'>
314 <class 'str'>
177 <class 'str'>
297 <class 'str'>
101 <class 'str'>
179 <class 'str'>
125 <class 'str'>
132 <class 'str'>
256 <class 'str'>
285 <class 'str'>
154 <class 'str'>
0 <class 'str'>
157 <class 'str'>
32 <class 'str'>
101 <class 'str'>
204 <class 'str'>
223 <class 'str'>
122 <class 'str'>
143 <class 'str'>
277 <class 'str'>
113 <class 'str'>
235 <class 'str'>
117 <class 'str'>
206 <class 'str'>
156 <class 'str'>
200 <class 'str'>
231 <class 'str'>
107 <class 'str'>
143 <class 'str'>
418 <class 'str'>
100 <class 'str'>
0 <class 'str'>
83 <class 'str'>
65 <class 'str'>
4 <class 'str'>
146 <class 'str'>
274 <class 'str'>
115 <class 'str'>
158 <class 'str'>
199 <class 'str'>
141 <class 'str'>
135 <class 'str'>
249 <class 'str'>
156 <class 'str'>
90 <class 'str'>
404 <class 'str'>
363 <class 'str'>
148 <class 'str'>
229 <class 'str'>
281 <class 'str'>
163 <class 'str'>
0 <class 'str'>
55 <class 'str'>
23 <class 'str'>
26 <class 'str'>
110 <class 'str'>
376 <class 'str'>
89 <class 'str'>
76 <class 'str'>
60 <class 'str'>
64 <class 'str'>
151 <class 'str'>
40 <class 'str'>
103 <class 'str'>
149 <class 'str'>
396 <class 'str'>
108 <class 'str'>
183 <class 'str'>
190 <class 'str'>
none <class 'str'>
94 <class 'str'>
0 <class 'str'>
76 <class 'str'>
71 <class 'str'>
none <class 'str'>
166 <class 'str'>
106 <class 'str'>
124 <class 'str'>
120 <class 'str'>
43 <class 'str'>
161 <class 'str'>
56 <class 'str'>
34 <class 'str'>
198 <class 'str'>
189 <class 'str'>
326 <class 'str'>
141 <class 'str'>
224 <class 'str'>
144 <class 'str'>
259 <class 'str'>
121 <class 'str'>
55 <class 'str'>
64 <class 'str'>
178 <class 'str'>
98 <class 'str'>
118 <class 'str'>
140 <class 'str'>
289 <class 'str'>
211 <class 'str'>
68 <class 'str'>
270 <class 'str'>
72 <class 'str'>
92 <class 'str'>
192 <class 'str'>
345 <class 'str'>
385 <class 'str'>
208 <class 'str'>
243 <class 'str'>
242 <class 'str'>
416 <class 'str'>
329 <class 'str'>
219 <class 'str'>
107 <class 'str'>
202 <class 'str'>
248 <class 'str'>
none <class 'str'>
261 <class 'str'>
310 <class 'str'>
269 <class 'str'>
229 <class 'str'>
811 <class 'str'>
271 <class 'str'>
321 <class 'str'>
519 <class 'str'>
578 <class 'str'>

         month      state Number of files      Date  year
0      Janeiro       Acre               0  1/1/1998  1998
1      Janeiro       Acre               0  1/1/1999  1999
2      Janeiro       Acre               0  1/1/2000  2000
3      Janeiro       Acre               0  1/1/2001  2001
4      Janeiro       Acre               0  1/1/2002  2002
...        ...        ...             ...       ...   ...
6449  Dezembro  Tocantins             128  1/1/2012  2012
6450  Dezembro  Tocantins              85  1/1/2013  2013
6451  Dezembro  Tocantins             223  1/1/2014  2014
6452  Dezembro  Tocantins             373  1/1/2015  2015
6453  Dezembro  Tocantins             119  1/1/2016  2016

[6454 rows x 5 columns]

In [1544]:
d={'none':0}
df['Number of files']=df['Number of files'].replace(d)
df

         month      state Number of files      Date  year
0      Janeiro       Acre               0  1/1/1998  1998
1      Janeiro       Acre               0  1/1/1999  1999
2      Janeiro       Acre               0  1/1/2000  2000
3      Janeiro       Acre               0  1/1/2001  2001
4      Janeiro       Acre               0  1/1/2002  2002
...        ...        ...             ...       ...   ...
6449  Dezembro  Tocantins             128  1/1/2012  2012
6450  Dezembro  Tocantins              85  1/1/2013  2013
6451  Dezembro  Tocantins             223  1/1/2014  2014
6452  Dezembro  Tocantins             373  1/1/2015  2015
6453  Dezembro  Tocantins             119  1/1/2016  2016

[6454 rows x 5 columns]

In [1545]:
df['Number of files']=df['Number of files'].astype(float)# we are conveting first float coz that is the base datatype after that we will convert int

In [1546]:
df['Number of files']=df['Number of files'].astype(int)

# How to change the name of column

d={"old_m"="new_name"}

df=df[column_name"].map(d)#map is used to rename or change the column name

In [1547]:
'''d={'Janeiro':'January',}
df=df['month'].map(d)#drawback :it will check the particular name and rename the rest values as NaN
df'''

"d={'Janeiro':'January',}\ndf=df['month'].map(d)#drawback :it will check the particular name and rename the rest values as NaN\ndf"

df['col_name'].replace('old_nmae','new_name')# for object data type

when the collumn is not object dictionnary

d={'old_name':"new_name}

df['col_name'].replace(d)

In [1548]:
df["month"] = df['month'].replace('Janeiro','January')
df

         month      state  Number of files      Date  year
0      January       Acre                0  1/1/1998  1998
1      January       Acre                0  1/1/1999  1999
2      January       Acre                0  1/1/2000  2000
3      January       Acre                0  1/1/2001  2001
4      January       Acre                0  1/1/2002  2002
...        ...        ...              ...       ...   ...
6449  Dezembro  Tocantins              128  1/1/2012  2012
6450  Dezembro  Tocantins               85  1/1/2013  2013
6451  Dezembro  Tocantins              223  1/1/2014  2014
6452  Dezembro  Tocantins              373  1/1/2015  2015
6453  Dezembro  Tocantins              119  1/1/2016  2016

[6454 rows x 5 columns]

In [1549]:
df['month'].unique()

array(['January', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho',
       'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
      dtype=object)

In [1550]:
d={'Janeiro':"January",'Fevereiro':'Febuary','Março':'March','Abril':'April','Maio':"may",'Junho':'June','Julho':'July','Agosto':'August','Setembro':"September", 'Outubro':'October','Novembro':'November','Dezembro':'December'}
df['month']=df['month'].replace(d)
df

         month      state  Number of files      Date  year
0      January       Acre                0  1/1/1998  1998
1      January       Acre                0  1/1/1999  1999
2      January       Acre                0  1/1/2000  2000
3      January       Acre                0  1/1/2001  2001
4      January       Acre                0  1/1/2002  2002
...        ...        ...              ...       ...   ...
6449  December  Tocantins              128  1/1/2012  2012
6450  December  Tocantins               85  1/1/2013  2013
6451  December  Tocantins              223  1/1/2014  2014
6452  December  Tocantins              373  1/1/2015  2015
6453  December  Tocantins              119  1/1/2016  2016

[6454 rows x 5 columns]

In [1551]:
df.drop_duplicates()

         month      state  Number of files      Date  year
0      January       Acre                0  1/1/1998  1998
1      January       Acre                0  1/1/1999  1999
2      January       Acre                0  1/1/2000  2000
3      January       Acre                0  1/1/2001  2001
4      January       Acre                0  1/1/2002  2002
...        ...        ...              ...       ...   ...
6449  December  Tocantins              128  1/1/2012  2012
6450  December  Tocantins               85  1/1/2013  2013
6451  December  Tocantins              223  1/1/2014  2014
6452  December  Tocantins              373  1/1/2015  2015
6453  December  Tocantins              119  1/1/2016  2016

[6421 rows x 5 columns]

# Check Null Values

In [1552]:
df.isnull().value_counts()# for the dataframe

month  state  Number of files  Date   year
False  False  False            False  False    6454
Name: count, dtype: int64

In [1553]:
df["Number of files"].isna().value_counts()

Number of files
False    6454
Name: count, dtype: int64

In [1555]:
#number of employee who got fired in the month of january
var=df.groupby('month')
fir=var.get_group('January')
(fir['Number of files']!=0).sum()

np.int64(466)

In [1560]:
#number of people who got fired in 2002 (need feature engineering)
var=df.groupby('year')
fir=var.get_group('2002')
(fir['Number of files']!=0).sum()

np.int64(297)

In [1562]:
#number of files in year 2001 in Tocantins
df[(df['state']=='Tocantins') & (df['year']==2001)]["Number of files"].sum()

np.int64(0)

# Filling Null Values

df.fillna(method='ffill'),for forword filling

df['column'].fillna(method='backfill),for backword filling

In [ ]:
# how to fill null values
df["Number of files"].fillna(0 ,inplace=True)

In [ ]:
df["Number of files"].isna().sum()

#to remove a column

df.drop(['Column_name'],axis=1)

to remove the rows which contin null values

 df.dropna(inplace=True)

to remove the rows

 df.drop(df.index[index])

In [ ]:
df = df.drop(["year"],axis=1)

#change the datatype of column

df['column_name']=df['column_name'].astype(data)

    to change the date we use datime
    
d.to_datetime(df["column"])# if the formate of one type only

pd.to_datetime("column",formate=%dd/%mm/%yyyy,errors="coerce"),

    if my date have 12-04-2022 or 23/01/2023

pd.to_datetime("column",formate=%dd/%mm/%yyyy,errors="coerce",formate="mixed")

In [ ]:
df["Date"]=pd.to_datetime(df["Date"])
df.info()

#function
df["Col_name"] = df['Col_name'].str.capitalize(), will captital the first letter

df["Col_name"] = df['Col_name'].str.strip(), will remove the trailing spaces

In [ ]:
import pandas as pd
dff=pd.read_excel("/content/employee_data.xlsx")
dff

#syntax to set the index
df.set_index("column_Name")

In [ ]:
dff.set_index('emp_id')

#syntax to set the index
df.set_index()

In [ ]:
dff.reset_index()

In [ ]:
#show mw the data of emplyees from 1st row till 10th row dept gender and employee
dff.loc[1:10,["department","gender","full_name"]]

In [ ]:
#get the name those who are male and working in sales
dff["full_name"][(dff["gender"]=="male") & (dff["department"]=="Sales")]

In [ ]:
#fetch the name those are parmanent and sal is more than 3lakhs
dff["full_name"][(dff["emp_status"]=="permanent") & (dff["salary"]>30000)]

In [ ]:
#give me he sum of null values in the entire dataframe
dff.isnull().sum().sum()

In [ ]:
# change the column in dataframe from full name to name and deptpartment to dept
d={"full_name":"Name","department":"dept"}
dff.rename(columns=d,inplace=True)
dff

In [ ]:
#remove duplicates from the data
dff.drop_duplicates(inplace=True)
dff

In [ ]:
#check is there any null values in employee status or not if null is there fill null
dff["emp_status"].isnull()
dff["emp_status"].fillna(dff["emp_status"].mode(),inplace=True)
dff

In [ ]:
#impute the null value in age column
dff['age'].fillna(dff['age'].mean(),inplace=True)
dff

In [ ]:
#convert the datatupe
dff["age"].astype(int)

In [ ]:
# change the 	exp_years
dff['exp_years'].fillna(dff["exp_years"].mean(),inplace=True)
dff

In [ ]:
dff['emp_status'].fillna(dff["emp_status"].mode(),inplace=True)
dff

In [ ]:
d={'emp_id':'employee_Id',"Name":"name","emp_status":"employeement_status"}
dff.rename(columns=d,inplace=True)
dff

# Rearrange a columns using index
a=[0,1,3,7,5,4,2,8]

df[df.columns[a]]

In [ ]:
new=["employee_Id","name","age","gender","dept","join_date","exp_years","salary","employeement_status"]
dff=dff[new]
dff

In [ ]:
#replace male and Male with M and female and female with F
dff["gender"].value_counts()

In [ ]:
d = {"female":"F", "male":"M", "Female":"F","Male":"M"}
dff["gender"] = dff["gender"].replace(d)

In [ ]:
dff

In [ ]:
#remove trailling space
dff["name"]=dff["name"].str.strip()
dff

In [ ]:
#replace specific values
dff["employeement_status"].isna().sum()

In [ ]:
#
dff["employeement_status"].fillna("contract",inplace=True)
dff

In [ ]:
#
dff["salary"].fillna(dff["salary"].median(),inplace=True)
dff

In [ ]:
#for forword filling
dff['join_date']=dff['join_date'].fillna(method='ffill')

In [ ]:
#
dff['join_date']=dff['join_date'].fillna(method='backfill')

In [ ]:
#
dff.drop_duplicates()

In [ ]:
#
dff['dept']=dff["dept"].str.capitalize()
dff

In [ ]:
#
dff.drop(["exp_years"],axis=1)

In [ ]:
#
dff=dff.drop(dff[dff["salary"]>80000].index,inplace=True)
dff

pd.concat := it combine the dataframe based on particular axis(vertically , horizontally).

pd.merge:= it can combines the dataframe based on commom cloumns (like sql joins )

#Feature Enginnering

In [ ]:
#
a={'name':['dipali','isha','sonam'],'math':[78,87,77],'science':[67,78,54],'computer':[89,90,88]}
d=pd.DataFrame(a)
d['percentage']=(d['math']+d['science']+d['computer']) /len(a)-1
print(d)

In [ ]:
#
d['grade']=""
for i in range(len(d["percentage"])):
  for j in range(len(d['name'])):
    if d['percentage'][i]>60:
          d['grade'][i]='A+'
    elif d['percentage'][i]<60:
      #  if i==j:
          d['grade'][i]='B+'
d

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/titanic.csv')
df

In [ ]:
#fetch the first name from the dataframe
df['NAME']=[i.split(",")[0] for i in df['name']]
df

In [ ]:
#add prfix at first
df['salutaion']=[i.split(',')[1].split('.')[0] for i in df['name']]
df

#Binning
df['column']=pd.cut(df['column'],bins[],labels[])